user_name = input("Enter your name")
print (user_name)
age = input ("Enter your age")
age = int(age)
print(age)
country = input ("Enter the country")
print (country)
car_brand = input ("Enter the car brand")
print (car_brand)
car_type = input ("Enter car_type")
print (car_type)
year_of_manufacture =input ("Enter the year_of_manufacture")
year_of_manufacture = int(year_of_manufacture)
print (year_of_manufacture)
color = input ("Enter the color")
print(color)
engine =input ("Enter engine power")
engine = str(engine + "KW")
print (engine)
price = input ("Enter the price")
price = int (price)
print(price)
dream = "Keep dreming:)"
print(dream)

