# Generated by Django 3.0.4 on 2020-03-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='favorite_song',
            new_name='star',
        ),
        migrations.AlterField(
            model_name='album',
            name='release_year',
            field=models.DateField(verbose_name='date release'),
        ),
    ]
