# Generated by Django 3.0.4 on 2020-03-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_auto_20200325_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='star',
            new_name='favorite_song',
        ),
    ]
